### ISSUE TITLE
[ws] BUS FAULT occurs when connect and disconnect websocket server for several times.

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1670] opened 2017-11-20 08:31 UTC
### Description

Try to connect and disconnect with websocket server for several times, `BUS FAULT` error will happen.

### Test Code

[WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js);
 
### Steps to Reproduction

 1. `make JS=samples/websockets/WebSocketServer.js BOARD=frdm_k64f`
 2. `cp outdir/frdm_k64f/zephyr.bin /media/<username>/MBED/`
 3. `node samples/websockets/NodeWebSocketClient.js`
 4. CTRL+C to disconnect 
 5. repeat steps 3 and 4(error happens after about 5 times).

### Actual Result

![selection_006](https://user-images.githubusercontent.com/19813546/33008929-0082013c-ce10-11e7-99c5-3c4df3fc28fe.png)

 ### Expected Result

 No error occurs.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | dcf56a9 | FRDM-K64F | Nov 20, 2017 | Fail

**Comment by jimmy-huang** [comment] 2018-01-18 18:59
@qiaojingx Is this reproducible with master, it seemed the original check was with Zephyr 1.9, but I can't reproduce this on Zephyr 1.10.  However, I do get ip route dropped on the linux time periodically, and I have to add route again.

**Comment by qiaojingx** [comment] 2018-01-19 02:34
Verifed with commit 4b23a47. This issue happens with a much lower reappearance rate now(disconnect for 10+times).
![selection_021](https://user-images.githubusercontent.com/19813546/35131725-c27336dc-fd02-11e7-9114-6a504cdf5404.png)
And if keep connection from the beginning, issue #1725 will occurs.

**Comment by jimmy-huang** [comment] 2018-01-19 18:09
@brianjjones and @jprestwo were able to reproduce this yesterday and root-caused this bug, so a patch is on the way, don't close this until that's in.

**Closed** 2018-01-23 01:01 UTC
Labels: P1, bug

**Comment by qiaojingx** [comment] 2018-01-25 02:32
Verified with commit 0c0af9b, not reproduced.
